### ISSUE TITLE
debug thread

### ISSUE THREAD

**Issue by condaatje** [JacKeTUs/hid-logitech-hidpp#1]
permissions might be mixed up

[acc-ff-delay.pcapng.txt](https://github.com/JacKeTUs/hid-logitech-hidpp/files/12581476/acc-ff-delay.pcapng.txt)
[ams2-ff-nodelay.pcapng.txt](https://github.com/JacKeTUs/hid-logitech-hidpp/files/12581477/ams2-ff-nodelay.pcapng.txt)

**Comment by condaatje** [comment]
[acc-async-noff.pcapng.txt](https://github.com/JacKeTUs/hid-logitech-hidpp/files/12581559/acc-async-noff.pcapng.txt)

**Comment by condaatje** [comment]
```
tester@tester ~/w/ffbtools (master) [2]> make all
cc -MMD -MP -Wall -Wextra -m32 -fPIC -shared src/ffbwrapper.c -o build/libffbwrapper-i386.so -lrt -ldl
In file included from /usr/include/features.h:392,
                 from /usr/include/dlfcn.h:22,
                 from src/ffbwrapper.c:28:
/usr/include/features-time64.h:20:10: fatal error: bits/wordsize.h: No such file or directory
   20 | #include <bits/wordsize.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: build/libffbwrapper-i386.so] Error 1

```

**Comment by condaatje** [comment]
trying this in custom steam launch command for acc

`/home/tester/wheels/ffbtools/bin/ffbwrap --throttling --logger=/home/tester/wheels/ffbwrap.log /dev/input/by-id/usb-Logitech_PRO_Racing_Wheel_2319WD040908-event-joystick -- %command%`

**Comment by Lawstorant** [comment]
I'll be happy to help as I'm a new owner of PRO wheel and pedals. I'll try to understand the code of the driver after I wake up and maybe we could further the efforts.

**Comment by Theogore** [comment]
I am also now the proud owner of PRO wheel and pedals. I'm not a programmer and I'm a novice when it comes to Linux but if I can be of any assistance, please let me know.

EDIT: I figured out how to download this repo and "make" the files, but I'm not sure what to do next. Any advice is appreciated.

**Comment by condaatje** [comment]
Hey, welcome! I have been happily racing ACC+VR on Arch with the Logitech G Pro DD wheel for a month or so now, all thanks to @JacKeTUs - this was one of our debugging threads from a while back and it is likely going to be misleading/confusing. Sorry I should have cleaned it up/closed it long ago. 

Why not join us in the Simracer Matrix room?

https://matrix.to/#/#simracer:matrix.org
